<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengaturan_model extends CI_Model
{

    public $table = 'tbl_pengaturan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->or_like('npsn', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('koordinat', $q);
	$this->db->or_like('apykeymap', $q);
	$this->db->or_like('kodepos', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('faks', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('youtube', $q);
	$this->db->or_like('twitter', $q);
	$this->db->or_like('google+', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_sekolah', $q);
	$this->db->or_like('npsn', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('provinsi', $q);
	$this->db->or_like('kabupaten', $q);
	$this->db->or_like('kecamatan', $q);
	$this->db->or_like('koordinat', $q);
	$this->db->or_like('apykeymap', $q);
	$this->db->or_like('kodepos', $q);
	$this->db->or_like('telepon', $q);
	$this->db->or_like('faks', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('facebook', $q);
	$this->db->or_like('youtube', $q);
	$this->db->or_like('twitter', $q);
	$this->db->or_like('google+', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pengaturan_model.php */
/* Location: ./application/models/Pengaturan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-13 07:10:35 */
/* http://harviacode.com */